ktor:
  application:
    modules:
      - io.github.lunarisworks.portalis.server.ApplicationKt.module
  deployment:
    port: $PORT:8080

postgres:
  host: "$POSTGRES_HOST:localhost"
  port: $POSTGRES_PORT:5432
  database: "$POSTGRES_DB:postgres"
  username: "$POSTGRES_USER:postgres"
  password: "$POSTGRES_PASSWORD:postgres"

security:
  jwt:
    realm: portalis
    issuer: $JWT_ISSUER:localhost:8080
    audience: $JWT_AUDIENCE:localhost:9090
    expires-in: $JWT_EXPIRES_IN:7d
    secret: $JWT_SECRET:jwt-secret-key
